version: 2
updates:
  # security update bot - weekly
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "security"
      include: "scope"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "security"
      - "enhancement"
    assignees:
      - "CubeVic"
    reviewers:
      - "CubeVic"
    groups:
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"

  # dependency update bot - Monthly
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Taipei"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "direct"
    versioning-strategy: auto
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "enhancement"
    assignees:
      - "CubeVic"
    reviewers:
      - "CubeVic"
    groups:
      pip-monthly:
        applies-to: version-updates
        patterns:
          - "*"